version: "3.2"
services:
  rest_app:
    build:
      dockerfile: Dockerfile.dev
      context: .
    ports:
      - 3000:3000
    depends_on:
      - mongo
    volumes:
      - /usr/src/app/node_modules
      - .:/usr/src/app
  mongo:
    image: mongo:latest
    command: --smallfiles
    ports:
      - 27017:27017
    volumes:
      - type: volume
        source: mongodb
        target: /data/db
volumes:
  mongodb:
